import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'login_dto.mapper.dart';

@MappableClass()
class LoginDto with LoginDtoMappable {
  LoginDto({
    required this.clientId,
    required this.username,
    required this.password,
  });

  final int clientId;
  final String username;
  final String password;
}
